### PR TITLE
typedefs for qty_t and volume_t

### PR DESCRIPTION
**Pull request by orens77**
allow floating-point quantities for backtest

### CODE REVIEW

**Comment by open-trade** [comment]
qty_t does not follow google c++ naming style

**Comment by open-trade** [comment]
please put  typedef in struct MarketData, use Qty and  Volume

**Comment by open-trade** [comment]
have you tried complile? seems compile not ok from your code

**Comment by orens77** [comment]
sorry -- I was trying to do too many things at once this morning and I got my terminal windows mixed up.  Very embarrassing.  I am also separately working on multithreading the backtest algos.

**Pull request merged**
